src/config/routes.rb
Rails.application.routes.draw do
  get 'static/help'

  get 'admin/mailer_test'

  resources :tricks
  get 'admin/bot'

  get 'admin/season'

  get 'admin/engine'

  resources :countries
  resources :cities
  resources :skaters
  resources :users

  resources :account_activations, only: [:edit]
  
  get "home/index"
  root :to => "home#index"

  namespace :cities do
    %w(index show).each do |action|
      get action, action: action
    end
  end

  namespace :admin do
    %w(index country user).each do |action|
      get action, action: action
    end
  end

  get '/home/result/:id', to: 'home#result'
  
  match '/search/result', to: 'search#result', via: 'get'
  
  match '/admin/new_engine_result', to: 'admin#new_engine_result', via: 'get'
  match '/admin/new_engine_result', to: 'admin#new_engine_result', via: 'post'

  match '/admin/new_bots', to: 'admin#new_bots', via: 'get'
  match '/admin/new_bots', to: 'admin#new_bots', via: 'post'

  match '/admin/new_season', to: 'admin#new_season', via: 'post'
  match '/admin/start_season/:id', to: 'admin#start_season', via: 'get'
  match '/admin/start_season/:id', to: 'admin#start_season', via: 'post'
  match '/admin/send_mail_test', to: 'admin#send_mail_test', via: 'post'

  get    '/admin',                          to: 'admin#index'
  get    '/admin/maintenance',              to: 'admin#maintenance'
  post   '/admin/add_instant_maintenance',  to: 'admin#add_instant_maintenance'
  post   '/admin/add_scheduled_maintenance',to:'admin#add_scheduled_maintenance'
  post  '/admin/delete_maintenance/:id',    to: 'admin#delete_maintenance'

  post '/skater/hire/:id', to: 'skaters#hire'
  post '/skater/dismiss/:id', to: 'skaters#dismiss'

 
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
end

src/app/models/skater.rb
# coding: utf-8
# Copyright 2012-2015, 2018-2019 Jérôme Pasquier
#
# This file is part of Sk8tycoon.
# 
# Sk8tycoon is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# Sk8tycoon is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with Sk8tycoon.  If not, see <http://www.gnu.org/licenses/>.


# The Skater model
class Skater < ActiveRecord::Base
  validates :first_name,  :presence => true
  validates :last_name,  :presence => true
  validates :street, :numericality => { :less_than_or_equal_to => 250 }
  validates :vert, :numericality => { :less_than_or_equal_to => 250 }
  validates :freestyle, :numericality => { :less_than_or_equal_to => 250 }

  belongs_to :city, foreign_key: 'hometown_id'
  belongs_to :country
  belongs_to :user
  
  # Returns this skater's hometown name
  def hometown
    begin
      City.find(self.hometown_id).name
    rescue ActiveRecord::RecordNotFound
      "No hometown found (id = #{self.hometown_id})"
    end
  end

  # Get a random newly-created Skater object
  def self.random!
    l = LastName.all.sample
    f = FirstName.where({country_id: l.country_id}).sample
    raise "Can't find FirstName for country.id #{l.country_id}" if f.nil?
    
    a = (14..35).to_a.sample

    fr = (20..250).to_a.sample
    s = (20..250).to_a.sample
    v = (20..250).to_a.sample

    # 1% of all skaters are 'X'
    se_r = rand * 99
    if se_r < 1
      se = 'X'
    else
      se = f.sex
    end

    # 5% have a random nationality
    nat = nil
    nat_r = rand * 99
    if nat_r < 5
      nat = Country.all.sample.id
    else
      nat = l.country_id
    end

    # Hometown
    #  h = City.all.sample
    h = City.from_country(nat)
    
    Skater.create({first_name: f.caption, last_name: l.caption,
                   age: a, freestyle: fr, street: s, vert: v,
                   hometown_id: h.id, country_id: nat,
                   sex: se})
  end
  
end

src/app/controllers/skaters_controller.rb
# coding: utf-8
# Copyright 2012-2015, 2018-2019 Jérôme Pasquier
#
# This file is part of Sk8tycoon.
# 
# Sk8tycoon is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# Sk8tycoon is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with Sk8tycoon.  If not, see <http://www.gnu.org/licenses/>.

require "#{Rails.root}/lib/engine.rb"


# The controller for Skater model
class SkatersController < ApplicationController
  # GET /skaters
  # GET /skaters.json
  def index
    @active_menu = "skaters"
    @skaters = Skater.paginate(:page => params[:page], :per_page => 20)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @skaters }
    end
  end

  # GET /skaters/1
  # GET /skaters/1.json
  def show
    @active_menu = "skaters"
    @skater = Skater.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @skater }
    end
  end

  # GET /skaters/new
  # GET /skaters/new.json
  def new
    @active_menu = "skaters"
    @skater = Skater.new
    @cities = City.all
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @skater }
    end
  end

  # GET /skaters/1/edit
  def edit
    @active_menu = "skaters"
    @skater = Skater.find(params[:id])
    @cities = City.all
  end

  # POST /skaters
  # POST /skaters.json
  def create
    @skater = Skater.new(skater_params)

    respond_to do |format|
      if @skater.save
        format.html { redirect_to @skater, notice: 'Skater was successfully created.' }
        format.json { render json: @skater, status: :created, location: @skater }
      else
        format.html { render action: "new" }
        format.json { render json: @skater.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /skaters/1
  # PUT /skaters/1.json
  def update
    @skater = Skater.find(params[:id])

    respond_to do |format|
      if @skater.update_attributes(params[:skater])
        format.html { redirect_to @skater, notice: 'Skater was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @skater.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /skaters/1
  # DELETE /skaters/1.json
  def destroy
    @skater = Skater.find(params[:id])
    @skater.destroy

    respond_to do |format|
      format.html { redirect_to skaters_url }
      format.json { head :no_content }
    end
  end

  # A user hire this skater
  def hire
    @skater = Skater.find(params[:id])
    user = User.find(current_user.id)
    price = params[:price].to_i

    if user.grip < price
      flash[:warning] = "You don't have enough grips to hire this skater.<br>
You only have #{user.grp} grips."
    else
      @skater.user = current_user
      @skater.save!

      user.update_grip! user.grip - price
      
      # Reload current page
      redirect_to skater_path(@skater)
    end
  end

    # You dismiss (stop o controll) this skater
  def dismiss
    @skater = Skater.find(params[:id])
    @skater.user = nil
    @skater.save!
    # Reload current page
    redirect_to skater_path(@skater)
  end

  private

  # A private method to help creating a valid skater once for all
  def skater_params
    params.require(:skater).permit(:first_name, :last_name, :age,
                                   :street, :vert, :freestyle,
                                   :bio_text, :hometown_id)
  end
  
end

src/app/helpers/skaters_helper.rb
# coding: utf-8
# Copyright 2012-2015, 2018-2019 Jérôme Pasquier
#
# This file is part of Sk8tycoon.
# 
# Sk8tycoon is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# Sk8tycoon is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with Sk8tycoon.  If not, see <http://www.gnu.org/licenses/>.

# The Skater helper
module SkatersHelper
  
  # Return a link to the given skater
  #
  # @param skater_object A skater model object
  def skater_name(skater_object, hired = true)
    "Retired Skater" if skater_object.nil?

    aze = ""

    if hired
      if skater_object.user == current_user and current_user
        aze = "<span class='badge badge-info'>hired</span>"
      end
    end
    
    name = "#{skater_object.first_name}&nbsp;#{skater_object.last_name} #{aze}"
           .html_safe
    link_to(name, controller: 'skaters', action: 'show', id: skater_object.id)

  end

end

src/app/views/skaters/_form.html.erb
<%= form_for(@skater) do |f| %>
  <% if @skater.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@skater.errors.count, "error") %> prohibited this skater from being saved:</h2>

      <ul>
      <% @skater.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :hometown %><br />
    <%= f.select(:hometown_id, @cities.map{|u| [u.name, u.id]}) %>
  </div>
  <div class="field">
    <%= f.label :bio_text %><br />
    <%= f.text_area :bio_text, :size => "30x10"%>
  </div>
  <div class="field">
    <%= f.label :age %><br />
    <%= f.number_field :age %>
  </div>
  <h2>Stats.</h2>
  <div class="field">
    <%= f.label :street %><br />
    <%= f.number_field :street %>
  </div>
  <div class="field">
    <%= f.label :vert %><br />
    <%= f.number_field :vert %>
  </div>
  <div class="field">
    <%= f.label :freestyle %><br />
    <%= f.number_field :freestyle %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

src/app/views/skaters/edit.html.erb
<h1>Editing skater</h1>

<%= render 'form' %>

<%= link_to 'Show', @skater %> |
<%= link_to 'Back', skaters_path %>

src/app/views/skaters/index.html.erb
<h1>Listing <%=@skaters.size %> skaters</h1>

<table class="sk8table">
  <caption>Skater list</caption>
  <thead>
    <tr>
      <th>Name</th>
      <th>Nationality</th>
      <th>City</th>
      <th>Age</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
<% @skaters.each do |skater| %>
  <tr>
    <td><%= skater_name(skater) %></td>
    <th><%= country_link(skater.country_id) %></th>
    <th><%= city_link(skater.hometown_id) %></th>
    <td><%= skater.age %></td>
    <td><%= link_to 'Show', skater %></td>
    <td><%= link_to 'Edit', edit_skater_path(skater) %></td>
    <td><%= link_to 'Destroy', skater, method: :delete, data:
	        { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
  </tbody>
</table>


<div class="digg_pagination">
  <div class="page_info">
    <%= page_entries_info @skaters %>
  </div>
  <%= will_paginate @skaters, :container => false %>
</div>

<br />

<%= link_to 'New Skater', new_skater_path %>

src/app/views/skaters/new.html.erb
<h1>New skater</h1>

<%= render 'form' %>

<%= link_to 'Back', skaters_path %>

src/app/views/skaters/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @skater.first_name %>  <%= @skater.last_name %></h1>
from <%= @skater.hometown %>, <small><%= @skater.age %> years old</small>


<%= sanitize(textilize(@skater.bio_text)) %>

<h1>Stats.</h1>
<h2>Surfaces :</h2>
<table>
  <tr>
    <td>street</td>
    <td>
      <canvas id="skaterStatStreet" width="123px" height="17px"></canvas>
      <script>draw_stats('skaterStatStreet', <%= @skater.street %>);</script>
    </td>
  </tr>
  <tr>
    <td>Vert.</td>
    <td>
      <canvas id="skaterStatVert" width="123px" height="17px"></canvas>
      <script>draw_stats('skaterStatVert', <%= @skater.vert %>);</script>
    </td>
  </tr>
  <tr>
    <td>Freestyle</td>
    <td>
      <canvas id="skaterStatFree" width="123px" height="17px"></canvas>
      <script>draw_stats('skaterStatFree', <%= @skater.freestyle %>);</script>
    </td>
  </tr>
</p>
</table>

<% if @skater.user.nil? %>

<%=
  form_for(:skater, url: "/skater/hire/#{@skater.id}") do |f|
    grip_button(10, "Hire me now!")
  end
%>
    
<% else %>
  <% if @skater.user == current_user %>
  <div class='owner'>This skater belongs to you</div>.

  <%=
    form_for(:skater, url: "/skater/dismiss/#{@skater.id}") do |f|
    f.submit("Dismiss!", class: "btn btn-primary")
    end
    %>

  
  <% else %>
<div class='owner'>This skater belongs to <%= @skater.user.name %></div>.
  <% end %>
<% end %>

<%= link_to 'Edit', edit_skater_path(@skater) %> |
<%= link_to 'Back', skaters_path %>