src/config/routes.rb
Rails.application.routes.draw do
  get 'static/help'

  get 'admin/mailer_test'

  resources :tricks
  get 'admin/bot'

  get 'admin/season'

  get 'admin/engine'

  resources :countries
  resources :cities
  resources :skaters
  resources :users

  resources :account_activations, only: [:edit]
  
  get "home/index"
  root :to => "home#index"

  namespace :cities do
    %w(index show).each do |action|
      get action, action: action
    end
  end

  namespace :admin do
    %w(index country user).each do |action|
      get action, action: action
    end
  end

  get '/home/result/:id', to: 'home#result'
  
  match '/search/result', to: 'search#result', via: 'get'
  
  match '/admin/new_engine_result', to: 'admin#new_engine_result', via: 'get'
  match '/admin/new_engine_result', to: 'admin#new_engine_result', via: 'post'

  match '/admin/new_bots', to: 'admin#new_bots', via: 'get'
  match '/admin/new_bots', to: 'admin#new_bots', via: 'post'

  match '/admin/new_season', to: 'admin#new_season', via: 'post'
  match '/admin/start_season/:id', to: 'admin#start_season', via: 'get'
  match '/admin/start_season/:id', to: 'admin#start_season', via: 'post'
  match '/admin/send_mail_test', to: 'admin#send_mail_test', via: 'post'

  get    '/admin',                          to: 'admin#index'
  get    '/admin/maintenance',              to: 'admin#maintenance'
  post   '/admin/add_instant_maintenance',  to: 'admin#add_instant_maintenance'
  post   '/admin/add_scheduled_maintenance',to:'admin#add_scheduled_maintenance'
  post  '/admin/delete_maintenance/:id',    to: 'admin#delete_maintenance'

  post '/skater/hire/:id', to: 'skaters#hire'
  post '/skater/dismiss/:id', to: 'skaters#dismiss'

 
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
end

src/app/models/trick.rb
# coding: utf-8
# Copyright 2012-2015, 2018-2019 Jérôme Pasquier
#
# This file is part of Sk8tycoon.
# 
# Sk8tycoon is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# Sk8tycoon is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with Sk8tycoon.  If not, see <http://www.gnu.org/licenses/>.

# The Trick model
#
# == Database values
#
#      string :name
#      integer :diff : /255 the overall difficulty for this trick
#      integer :street  /255 Is this a street 
#      integer :vert
#      integer :freestyle
class Trick < ApplicationRecord

  # Returns an array of tricks name
  def self.to_a
    a = Array.new
    Trick.all.each do |t|
      a << t.name
    end
    a
  end
end

src/app/controllers/tricks_controller.rb
# coding: utf-8
# Copyright 2012-2015, 2018-2019 Jérôme Pasquier
#
# This file is part of Sk8tycoon.
# 
# Sk8tycoon is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# Sk8tycoon is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with Sk8tycoon.  If not, see <http://www.gnu.org/licenses/>.

class TricksController < ApplicationController
  before_action :set_trick, only: [:show, :edit, :update, :destroy]

  # GET /tricks
  def index
    @active_menu = "tricks"
    @tricks = Trick.paginate(:page => params[:page], :per_page => 20)
  end

  # GET /tricks/1
  def show
    @active_menu = "tricks"
  end

  # GET /tricks/new
  def new
    @trick = Trick.new
  end

  # GET /tricks/1/edit
  def edit
    @active_menu = "tricks"
  end

  # POST /tricks
  def create
    @trick = Trick.new(trick_params)

    if @trick.save
      redirect_to @trick, notice: 'Trick was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /tricks/1
  def update
    if @trick.update(trick_params)
      redirect_to @trick, notice: 'Trick was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /tricks/1
  def destroy
    @trick.destroy
    redirect_to tricks_url, notice: 'Trick was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trick
      @trick = Trick.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def trick_params
      params.require(:trick).permit(:name, :diff, :street, :vert, :freestyle)
    end
end

src/app/helpers/tricks_helper.rb
# coding: utf-8
# Copyright 2012-2015, 2018-2019 Jérôme Pasquier
#
# This file is part of Sk8tycoon.
# 
# Sk8tycoon is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# Sk8tycoon is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with Sk8tycoon.  If not, see <http://www.gnu.org/licenses/>.

# The Trick model helper
module TricksHelper
end

src/app/views/tricks/_form.html.erb
<%= form_with(model: trick, local: true) do |form| %>
  <% if trick.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(trick.errors.count, "error") %> prohibited this trick from being saved:</h2>

      <ul>
      <% trick.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :trick_name %>
  </div>

  <div class="field">
    <%= form.label :diff %>
    <%= form.number_field :diff, id: :trick_diff %>
  </div>

  <div class="field">
    <%= form.label :street %>
    <%= form.text_field :street, id: :trick_street %>
  </div>

  <div class="field">
    <%= form.label :vert %>
    <%= form.text_field :vert, id: :trick_vert %>
  </div>

  <div class="field">
    <%= form.label :freestyle %>
    <%= form.text_field :freestyle, id: :trick_freestyle %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

src/app/views/tricks/edit.html.erb
<h1>Editing Trick</h1>

<%= render 'form', trick: @trick %>

<%= link_to 'Show', @trick %> |
<%= link_to 'Back', tricks_path %>

src/app/views/tricks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tricks</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Diff</th>
      <th>Street</th>
      <th>Vert</th>
      <th>Freestyle</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tricks.each do |trick| %>
      <tr>
        <td><%= trick.name %></td>
        <td><%= trick.diff %></td>
        <td><%= trick.street %></td>
        <td><%= trick.vert %></td>
        <td><%= trick.freestyle %></td>
        <td><%= link_to 'Show', trick %></td>
        <td><%= link_to 'Edit', edit_trick_path(trick) %></td>
        <td><%= link_to 'Destroy', trick, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div class="digg_pagination">
  <div class="page_info">
    <%= page_entries_info @tricks %>
  </div>
  <%= will_paginate @tricks, :container => false %>
</div>


<%= link_to 'New Trick', new_trick_path %>

src/app/views/tricks/new.html.erb
<h1>New Trick</h1>

<%= render 'form', trick: @trick %>

<%= link_to 'Back', tricks_path %>

src/app/views/tricks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @trick.name %>
</p>

<p>
  <strong>Diff:</strong>
  <%= @trick.diff %>
</p>

<p>
  <strong>Street:</strong>
  <%= @trick.street %>
</p>

<p>
  <strong>Vert:</strong>
  <%= @trick.vert %>
</p>

<p>
  <strong>Freestyle:</strong>
  <%= @trick.freestyle %>
</p>

<%= link_to 'Edit', edit_trick_path(@trick) %> |
<%= link_to 'Back', tricks_path %>