src/config/routes.rb
Rails.application.routes.draw do
  get 'static/help'

  get 'admin/mailer_test'

  resources :tricks
  get 'admin/bot'

  get 'admin/season'

  get 'admin/engine'

  resources :countries
  resources :cities
  resources :skaters
  resources :users

  resources :account_activations, only: [:edit]
  
  get "home/index"
  root :to => "home#index"

  namespace :cities do
    %w(index show).each do |action|
      get action, action: action
    end
  end

  namespace :admin do
    %w(index country user).each do |action|
      get action, action: action
    end
  end

  get '/home/result/:id', to: 'home#result'
  
  match '/search/result', to: 'search#result', via: 'get'
  
  match '/admin/new_engine_result', to: 'admin#new_engine_result', via: 'get'
  match '/admin/new_engine_result', to: 'admin#new_engine_result', via: 'post'

  match '/admin/new_bots', to: 'admin#new_bots', via: 'get'
  match '/admin/new_bots', to: 'admin#new_bots', via: 'post'

  match '/admin/new_season', to: 'admin#new_season', via: 'post'
  match '/admin/start_season/:id', to: 'admin#start_season', via: 'get'
  match '/admin/start_season/:id', to: 'admin#start_season', via: 'post'
  match '/admin/send_mail_test', to: 'admin#send_mail_test', via: 'post'

  get    '/admin',                          to: 'admin#index'
  get    '/admin/maintenance',              to: 'admin#maintenance'
  post   '/admin/add_instant_maintenance',  to: 'admin#add_instant_maintenance'
  post   '/admin/add_scheduled_maintenance',to:'admin#add_scheduled_maintenance'
  post  '/admin/delete_maintenance/:id',    to: 'admin#delete_maintenance'

  post '/skater/hire/:id', to: 'skaters#hire'
  post '/skater/dismiss/:id', to: 'skaters#dismiss'

 
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
end

src/app/views/layouts/_maintenance.haml
- if in_maintenance()
  %div{class: "alert alert-warning", role: "alert", id: "in-maintenance"}
    %h1 Maintenance mode
    %p Sk8tycoon is actually in maintenance. Please come back later.
    %p
      Administrator message is
      «
      %em= get_maintenance().comment
      »

src/app/views/layouts/_menu.html.erb
<nav  class="navbar fixed-top navbar-dark bg-dark bg-faded navbar-expand-md">
  <a href="/" class="navbar-brand">
<!--    <img id="logo" src="/assets/logo.png" /> -->
  <%= image_tag("logo.png", border: 0) %>
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse"
	  data-target="#navbarSupportedContent"
	  aria-controls="navbarSupportedContent" aria-expanded="false"
	  aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <%= menu_item(@active_menu, "Skaters",   skaters_path) %>
      <%= menu_item(@active_menu, "Cities",    cities_path) %>
      <%= menu_item(@active_menu, "Countries", countries_path) %>
      <%= menu_item(@active_menu, "Tricks",    tricks_path) %>
    </ul>
    
    <% if is_admin? %>
      <ul class="navbar-nav ml-auto">
        <%= menu_item(@active_menu, "Admin", "/admin") %>
      </ul>
    <% end %>

    
    <% if is_admin? %>
    <!-- For test purpose only -->
    <%= form_tag("/search/result", :method => "get",
         class: "form-inline my-2 my-lg-0") do %>
    <%= text_field_tag :q ,'' , {:id => "search-entry" ,
    class: "form-control mr-sm-2", type: "search",
    placeholder: "Search"} %>
    <%= button_to "Search", {:controller => 'search',:action => "result"}, 
    {class: "btn btn-outline-success my-2 my-sm-0"} %> 
    <% end %>
    <% end %>

      
  </div>
</nav>

src/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sk8tycoon</title>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <!--[if !IE 7]>
	<style type="text/css">
		#wrap {display:table;height:100%}
	</style>
	<![endif]-->
  <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= favicon_link_tag image_path("logo.ico") %>
</head>
<body class="<%= skin_class() %>">
  <select id="skin"></select>
  <%= render :partial => 'layouts/menu' %>
  <main class="container-fluid">
    <% if notice %>
    <%= notice %>
    <% end %>
	
    <% if alert %>
    <%= alert %>
    <% end %>

    <% flash.each do |message_type, message| %>
    <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
    <% end %>

      
  <div class="row">
    <div class="col-9" id="content">
      <% if not logged_in? then %>
        <%= render :partial => 'layouts/maintenance' %>
        <%= yield %>
        </div>
        <div class="col-3" id="sidebar">
        <% if logged_in? %>
          <%= render :partial => 'widgets/me' %>
          <%= render :partial => 'widgets/admin' %>
        <% else %>
          <%= render :partial => 'widgets/login' %>
        <% end %>
  	</div>
      <% else %>
	<%= render :partial => 'layouts/maintenance' %>
        <%= yield %>
        </div> <!-- col-8 -->
        <div class="col-3" id="sidebar">
          <%= render :partial => 'widgets/season' %>

          <% if logged_in? %>
            <%= render :partial => 'widgets/me' %>
          <% else %>
            <%= render :partial => 'widgets/login' %>
          <% end %>

          <% if is_admin? %>
            <%= render :partial => 'widgets/admin' %>
          <% end %>
        <% end %>
    </div><!-- sidebar -->  
  </div> <!-- row -->
    <% if is_admin? %>
    <%= debug(params) if Rails.env.development? %>
    <% end %>
</main><!-- container -->
<footer class="fixed-bottom footer">
  <p>Copyright (C) 2012 - 2019 Jérôme Pasquier <em>sk8tycoon.org</em>
    is Free Software licensed under AGPL &mdash; <a href="https://gitlab.com/solebull/sk8tycoon">https://gitlab.com/solebull/sk8tycoon</a></p>
</footer>
</body>
</html>