src/config/routes.rb
Rails.application.routes.draw do
  get 'static/help'

  get 'admin/mailer_test'

  resources :tricks
  get 'admin/bot'

  get 'admin/season'

  get 'admin/engine'

  resources :countries
  resources :cities
  resources :skaters
  resources :users

  resources :account_activations, only: [:edit]
  
  get "home/index"
  root :to => "home#index"

  namespace :cities do
    %w(index show).each do |action|
      get action, action: action
    end
  end

  namespace :admin do
    %w(index country user).each do |action|
      get action, action: action
    end
  end

  get '/home/result/:id', to: 'home#result'
  
  match '/search/result', to: 'search#result', via: 'get'
  
  match '/admin/new_engine_result', to: 'admin#new_engine_result', via: 'get'
  match '/admin/new_engine_result', to: 'admin#new_engine_result', via: 'post'

  match '/admin/new_bots', to: 'admin#new_bots', via: 'get'
  match '/admin/new_bots', to: 'admin#new_bots', via: 'post'

  match '/admin/new_season', to: 'admin#new_season', via: 'post'
  match '/admin/start_season/:id', to: 'admin#start_season', via: 'get'
  match '/admin/start_season/:id', to: 'admin#start_season', via: 'post'
  match '/admin/send_mail_test', to: 'admin#send_mail_test', via: 'post'

  get    '/admin',                          to: 'admin#index'
  get    '/admin/maintenance',              to: 'admin#maintenance'
  post   '/admin/add_instant_maintenance',  to: 'admin#add_instant_maintenance'
  post   '/admin/add_scheduled_maintenance',to:'admin#add_scheduled_maintenance'
  post  '/admin/delete_maintenance/:id',    to: 'admin#delete_maintenance'

  post '/skater/hire/:id', to: 'skaters#hire'
  post '/skater/dismiss/:id', to: 'skaters#dismiss'

 
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
end

src/app/views/widgets/_admin.html.erb
<div class="widget">
  <h1>Administration menu</h1>
    <ul>
      <li>
	<%= link_to("Administration main page", controller: 'admin') %>
      </li>
    </ul>
    <h1>Country Administration</h1>
    <ul>
      <li>
	<%= link_to("Countries without population", controller: 'admin', 
	action: "country", anchor: "without-population") %></li>
      <li>
	<%= link_to("Countries without city", controller: 'admin', 
	action: "country", anchor: "without-city") %></li>
    </ul>
    <h1>Miscelaneous</h1>
    <ul>
      <li>
	<%= link_to("Engine test", controller: 'admin',
	    action: "engine") %></li>
      <li>
	<%= link_to("Season administration", controller: "admin",
	    action: "season") %></li>
      <li>
	<%= link_to("Bot administration", controller: "admin",
	    action: "bot") %></li>

      <li>
	<%= link_to("Users administration", controller: "admin",
	    action: "user") %></li>

      <li><%= link_to("Mailer test", admin_mailer_test_path) %></li>
      <li><%= link_to("Maintenance", admin_maintenance_path) %></li>
    </ul>
</div><!-- widget -->

src/app/views/widgets/_login.html.erb
<div class="widget">
  <h1>Login</h1>
  <div class="row">
    <div class="col-md-12">

      <%= render 'shared/login_form' %>

    </div>
  </div>
</div>

src/app/views/widgets/_me.html.erb
<div class="widget">
  <h1>Me</h1>

  <p>You have <%= current_user.grip %> grips.
  
  <li><%= link_to "Profile", current_user %></li>
  <li><%= link_to "Settings", '#' %></li>
  <li><%= link_to "Log out", logout_path, method: :delete %></li>
  <%= link_to "Profile", current_user %>

  <h1>My Skaters</h1>

  <% if current_user.skaters.empty? %>
  <div class="alert alert-primary" role="alert">
    You don't have any skater. Go to
    <%= link_to "Skaters list", skaters_path %>
    to hire some.
  </div>
  <% else %>
  <table>
    <tr><th>Skater name</th><th>Nationality</th></tr>
    <% current_user.skaters.each do |s| %>
    <tr>
      <td><%= skater_name(s, false) %> </td>
      <td><%= country_link(s.country_id) %> </td>
    </tr>
    <% end %>
  </table>
<% end %>
  
</div><!-- widget -->
<div class="widget">
  
  <h1>My network</h1>
  This is second widget that contains a table :
</div><!-- widget -->

src/app/views/widgets/_season.html.erb
<div class="widget">
  <% if Season.actual.nil? then %>
  <h1>Season x</h1>
  <div class="alert alert-danger" role="alert">
    <%= Season.seed_error %>
  </div>
  <% else %>
    <h1>Season <%= Season.actual.num %></h1>
    <p>Week : <span id="season-week"></span><br>
    Day :  <span id="season-day"></span><br>
    Hour : <span id="season-hour"></span>
      <script>season_widget(<%= Season.actual.start %>);</script>
  <% end %>

</div><!-- widget -->